-- JSO @11-DIC-2018 * Pet. 68913/68914: IFRS9
-- JSO @10-JUL-2019 * Pet. 71266 - Se cambia la estructura 

IF OBJECT_ID('IFRS_DQ') IS NOT NULL 
BEGIN
    
	DROP TABLE IFRS_DQ	
	
END	
GO	
	
IF OBJECT_ID('IFRS_DQ') IS NULL 
BEGIN

	/* JSO@11-DIC-2018
	CREATE TABLE IFRS_DQ 
	(
		ID_DQ			VARCHAR(15)	,
		DESCRIPCION		VARCHAR(350),
		CAMPO			VARCHAR(30),
		HABILITADA	 	CHAR(1),
		CONDICION		VARCHAR(1000),
		ID_TABLA		INT,
		FECHA_UTL_MOD	DATETIME default GETDATE()
	)
	
	*/

	-- JSO@10-JUL-2019
	CREATE TABLE IFRS_DQ 
	(
		ID_DQ					VARCHAR(15)	,
		DESCRIPCION		VARCHAR(350),
		CAMPO					VARCHAR(30),
		HABILITADA	 		CHAR(1),
		QUERY					VARCHAR(1000),
		INTERFAZ				VARCHAR(30),
		FECHA_UTL_MOD	DATETIME default GETDATE()
	)
END

GO	

 IF OBJECT_ID('IFRS_DQ') IS NOT NULL 
BEGIN
    PRINT "TABLE IFRS_DQ CREATED"
END

GO 